# Site settings
title: ThinkR - Tools
email: colin@thinkr.fr
url: https://thinkr-open.github.io
description: "Open Source Tools, by ThinkR"
keywords: "R, RStats, Shiny, Development"
skills: "Open Source Tools, by ThinkR"
meta_author: ThinkR

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 313843 #80B3FF
  primary-rgb: "49,56,67" #"128,179,255"
  secondary: 3c3b42 #FD6E8A
  secondary-dark: 15b7d6 #A2122F

# Footer settings
footer:
  copyright: ThinkR
  location: ThinkR
  social: On the Web
  credits: About this page

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thinkr_fr
  - title: github
    url: http://github.com/ThinkR-open

# Postal address (add as many lines as necessary)
address:
  - line: contact@thinkr.fr
  - line: ---
  - line: 50 rue arthur rimbaud
  - line: 93300 aubervilliers

# Credits content
credits: 'Site built with Jekyll, based on the <a href = "https://github.com/jeromelachaud/freelancer-theme"><span style = "color:#ffffff">Freelancer Theme</span></a>.'

# Build settings
markdown: kramdown
permalink: pretty
